import { DimensionKey, GlossaryTerm, Question, ScaleOption } from '@/lib/types';

export const AGENCIES = [
  'ROGER',
  'LUPE',
  'AMPLIFY',
  'OMD',
  'NASTA',
  'BRICK',
  'ROW',
  'BPR',
] as const;

export const DIMENSIONS: DimensionKey[] = [
  'strategy',
  'process',
  'research',
  'craft',
  'operations',
];

export const DIMENSION_LABELS: Record<DimensionKey, string> = {
  strategy: 'Estrategia y negocio',
  process: 'Procesos de trabajo',
  research: 'Insights y audiencias',
  craft: 'Craft creativo',
  operations: 'Operación y gobierno',
};

export const DIMENSION_DESCRIPTIONS: Record<DimensionKey, string> = {
  strategy: 'Cómo el diseño influye en la propuesta de valor, la construcción de soluciones y la agenda de negocio.',
  process: 'Cómo se estructura el trabajo desde el brief hasta la entrega, evitando retrabajo y pérdida de contexto.',
  research: 'Cómo se entiende a clientes, audiencias y prospectos para diseñar soluciones más pertinentes.',
  craft: 'Cómo se sostiene la calidad creativa, visual y de experiencia en distintas cuentas y equipos.',
  operations: 'Cómo se gestiona la capacidad, la priorización, la claridad de roles y la mejora continua.',
};

export const DIMENSION_INTROS: Record<DimensionKey, string> = {
  strategy: 'En TEXO esta dimensión ayuda a ver si el diseño ya está entrando en la conversación de nuevos productos, propuestas y decisiones relevantes, o si todavía participa tarde y de forma táctica.',
  process: 'Acá evaluamos si la forma de trabajar permite empatizar con clientes y prospectos antes de producir piezas o presentaciones, y si el proceso sostiene consistencia entre creatividad, medios y estrategia.',
  research: 'Esta dimensión mira si la agencia usa insights, data, aprendizaje y observación real de audiencias para definir soluciones a medida, en lugar de resolver solo por intuición.',
  craft: 'Mide la calidad de ejecución, el estándar creativo compartido y si el valor del diseño se sostiene más allá del talento individual.',
  operations: 'Evalúa si el sistema puede escalar: claridad de roles, visibilidad del trabajo, capacidad, desarrollo de talento y gobierno para sostener la transformación.',
};

export const DIMENSION_WEIGHTS: Record<DimensionKey, number> = {
  strategy: 0.3,
  process: 0.25,
  research: 0.15,
  craft: 0.15,
  operations: 0.15,
};

export const SCALE_OPTIONS: ScaleOption[] = [
  {
    value: 1,
    shortLabel: 'Reactive',
    title: '1 · Reactivo',
    description: 'No existe, depende de personas o ocurre tarde.',
  },
  {
    value: 2,
    shortLabel: 'Emerging',
    title: '2 · Emergente',
    description: 'Sucede a veces, pero sin consistencia ni responsables claros.',
  },
  {
    value: 3,
    shortLabel: 'Defined',
    title: '3 · Definido',
    description: 'Existe de forma repetible en parte importante de la operación.',
  },
  {
    value: 4,
    shortLabel: 'Managed',
    title: '4 · Gestionado',
    description: 'Está sistematizado, se gestiona y se mide.',
  },
  {
    value: 5,
    shortLabel: 'Strategic',
    title: '5 · Estratégico',
    description: 'Es una capacidad madura que influye en negocio y ventaja competitiva.',
  },
];

export const GLOSSARY_TERMS: GlossaryTerm[] = [
  {
    id: 'design-thinking',
    term: 'Pensamiento de diseño',
    definition: 'Forma de resolver problemas poniendo primero la comprensión profunda de personas, contexto y necesidad antes de proponer soluciones.',
    appliedExample: 'En una agencia significa entender qué frena a un cliente o prospecto antes de armar una propuesta, campaña o producto nuevo.',
  },
  {
    id: 'discovery',
    term: 'Discovery',
    definition: 'Etapa inicial donde se entiende el problema, se relevan necesidades y se alinean objetivos antes de producir o diseñar.',
    appliedExample: 'Antes de desarrollar una propuesta para una cuenta, el equipo conversa con estrategia, medios y cliente para validar el problema real.',
  },
  {
    id: 'insight',
    term: 'Insight',
    definition: 'Aprendizaje útil sobre comportamientos, tensiones, motivaciones o decisiones de las audiencias.',
    appliedExample: 'No es solo una métrica de campaña; es descubrir qué mueve a una audiencia a elegir, mirar, confiar o actuar.',
  },
  {
    id: 'customer-centric',
    term: 'Customer centric',
    definition: 'Enfoque que organiza soluciones, procesos y experiencias alrededor de necesidades reales del cliente o usuario.',
    appliedExample: 'Implica adaptar propuestas, entregables y presentaciones a cada cuenta en vez de repetir una lógica estándar para todos.',
  },
  {
    id: 'handoff',
    term: 'Handoff',
    definition: 'Momento en que un equipo entrega contexto, definiciones y materiales a otro para que continúe el trabajo sin pérdida de información.',
    appliedExample: 'Por ejemplo, cuando estrategia y creatividad entregan un marco claro a medios o producción para evitar retrabajo.',
  },
  {
    id: 'governance',
    term: 'Gobierno',
    definition: 'Conjunto de reglas, roles, criterios y rituales que ordenan cómo se decide, prioriza y hace seguimiento.',
    appliedExample: 'Define quién aprueba, cómo se escalan bloqueos y qué indicadores se miran para mejorar.',
  },
];

export const QUESTIONS: Question[] = [
  {
    id: 'strategy_vision',
    dimension: 'strategy',
    title: 'Participación del diseño en nuevas soluciones',
    description: 'El diseño participa en la definición de propuestas, productos o soluciones para clientes antes de entrar en ejecución.',
    tooltip: 'Mide si el diseño entra en la conversación desde el problema y no solo al final para “embellecer”.',
    glossary: 'Relaciona diseño con desarrollo de propuestas, innovación y ventaja competitiva.',
    agencyExample: 'Ejemplo: antes de armar una propuesta comercial, creatividad, estrategia y diseño exploran juntos la necesidad del cliente y distintas formas de resolverla.',
    weight: 1.2,
  },
  {
    id: 'strategy_leadership',
    dimension: 'strategy',
    title: 'Patrocinio real del directorio',
    description: 'La dirección y los líderes impulsan activamente el diseño y el pensamiento de diseño como parte de la transformación del negocio.',
    tooltip: 'No alcanza con apoyo discursivo: debe reflejarse en decisiones, agenda y recursos.',
    glossary: 'Evalúa si el directorio solo declara intención o si realmente instala el diseño en la gestión.',
    agencyExample: 'Ejemplo: el directorio revisa iniciativas de customer centric, rediseño de procesos y nuevos productos con diseño presente en la mesa.',
    weight: 1.2,
  },
  {
    id: 'strategy_prioritization',
    dimension: 'strategy',
    title: 'Criterios claros para priorizar',
    description: 'Las iniciativas de diseño se priorizan con criterios visibles y conectados al valor para clientes, prospectos y negocio.',
    tooltip: 'Busca ver si el orden de trabajo responde a impacto y no solo a urgencias o pedidos sueltos.',
    agencyExample: 'Ejemplo: se decide dónde poner foco según potencial de negocio, complejidad, urgencia comercial y valor para la cuenta.',
    weight: 1,
  },
  {
    id: 'strategy_kpis',
    dimension: 'strategy',
    title: 'Medición del impacto de diseño',
    description: 'El diseño se mide con indicadores concretos, más allá de la percepción subjetiva del resultado.',
    tooltip: 'Puede incluir satisfacción, velocidad, retrabajo, tasa de aprobación, NPS interno o impacto comercial.',
    agencyExample: 'Ejemplo: además del NPS sobre diseño, se observa retrabajo, tiempos de ciclo o calidad percibida por cliente.',
    weight: 1.1,
  },
  {
    id: 'strategy_portfolio',
    dimension: 'strategy',
    title: 'Diseño en decisiones de portfolio',
    description: 'La mirada de diseño influye en qué nuevos productos, capacidades o propuestas conviene desarrollar.',
    tooltip: 'Evalúa si diseño ayuda a decidir hacia dónde crecer y no solo a resolver entregables.',
    agencyExample: 'Ejemplo: al evaluar una nueva oferta en content, CX o plataformas, diseño participa en la definición del enfoque y del valor diferencial.',
    weight: 1,
  },
  {
    id: 'process_briefs',
    dimension: 'process',
    title: 'Briefs claros y accionables',
    description: 'Los proyectos comienzan con briefs que explican contexto, problema, audiencia, objetivo y criterio de éxito.',
    tooltip: 'Un buen brief reduce retrabajo y alinea expectativas entre áreas.',
    agencyExample: 'Ejemplo: antes de diseñar una presentación o campaña, el equipo sabe qué problema de negocio resuelve, para quién y con qué objetivo.',
    weight: 1.1,
  },
  {
    id: 'process_discovery',
    dimension: 'process',
    title: 'Discovery antes de ejecutar',
    description: 'Existe una instancia real para entender el problema antes de entrar en creatividad, contenido o medios.',
    tooltip: 'Mide si hay tiempo y método para pensar antes de producir.',
    glossary: 'Discovery significa entender el problema antes de proponer soluciones.',
    agencyExample: 'Ejemplo: el equipo se toma un espacio corto para mapear audiencias, necesidades y tensiones antes de definir la propuesta.',
    weight: 1.2,
  },
  {
    id: 'process_collaboration',
    dimension: 'process',
    title: 'Trabajo integrado entre áreas',
    description: 'Estrategia, cuentas, creatividad, medios, contenido y diseño trabajan con intercambio real y no en silos.',
    tooltip: 'La calidad del resultado depende de cómo se conecta el sistema completo.',
    agencyExample: 'Ejemplo: una propuesta para un prospecto se trabaja con una lógica integrada entre medios, creatividad y diseño de experiencia.',
    weight: 1,
  },
  {
    id: 'process_reviews',
    dimension: 'process',
    title: 'Rituales de revisión',
    description: 'Hay instancias de revisión que ayudan a mejorar el trabajo antes de salir a cliente o producción.',
    tooltip: 'La revisión consistente evita que la calidad dependa solo del último minuto.',
    agencyExample: 'Ejemplo: el equipo tiene checkpoints para revisar claridad de la solución, narrativa, experiencia y consistencia de la presentación.',
    weight: 1,
  },
  {
    id: 'process_handoff',
    dimension: 'process',
    title: 'Handoff con contexto',
    description: 'Las entregas entre áreas minimizan retrabajo y pérdida de contexto.',
    tooltip: 'Evalúa si el trabajo se transfiere con definiciones claras, responsables y materiales útiles.',
    glossary: 'Handoff es el traspaso entre equipos o etapas sin perder contexto.',
    agencyExample: 'Ejemplo: cuando un proyecto pasa de estrategia a creatividad o a medios, todos reciben el racional, los objetivos y las decisiones tomadas.',
    weight: 1,
  },
  {
    id: 'research_customer',
    dimension: 'research',
    title: 'Comprensión real de clientes y audiencias',
    description: 'El equipo entiende motivaciones, fricciones y comportamientos de clientes, prospectos y audiencias antes de diseñar soluciones.',
    tooltip: 'Busca ver si se empatiza de verdad o si se trabaja desde supuestos.',
    agencyExample: 'Ejemplo: antes de proponer un producto o campaña, se identifican tensiones del cliente y necesidades específicas del decisor y su audiencia.',
    weight: 1.1,
  },
  {
    id: 'research_testing',
    dimension: 'research',
    title: 'Validación antes de escalar',
    description: 'Se testean hipótesis, conceptos, experiencias o piezas antes de multiplicar inversión y esfuerzo.',
    tooltip: 'No todo necesita investigación compleja, pero sí aprendizaje antes de escalar.',
    agencyExample: 'Ejemplo: se valida una narrativa de propuesta, un contenido o una lógica de experiencia con feedback rápido antes de presentarla.',
    weight: 1.2,
  },
  {
    id: 'research_data_use',
    dimension: 'research',
    title: 'Uso útil de data e insights',
    description: 'La data, el NPS, los hallazgos de clientes o las métricas de medios se usan para tomar decisiones.',
    tooltip: 'La pregunta no es si hay data, sino si cambia lo que se hace con ella.',
    agencyExample: 'Ejemplo: si el NPS de diseño cae o una presentación tiene baja conversión, el equipo aprende y ajusta la forma de trabajar.',
    weight: 1.1,
  },
  {
    id: 'research_documentation',
    dimension: 'research',
    title: 'Memoria compartida de aprendizaje',
    description: 'Los aprendizajes se documentan y quedan disponibles para futuras cuentas, propuestas o productos.',
    tooltip: 'Mide si el conocimiento queda en el sistema o se pierde en conversaciones sueltas.',
    agencyExample: 'Ejemplo: una agencia deja registrados patrones de éxito, objeciones frecuentes y aprendizajes de clientes para usarlos después.',
    weight: 0.9,
  },
  {
    id: 'research_feedback_loop',
    dimension: 'research',
    title: 'Aprendizaje que cambia decisiones',
    description: 'Los hallazgos se traducen en cambios concretos de proceso, oferta, narrativa o experiencia.',
    tooltip: 'El aprendizaje sirve cuando cambia algo, no cuando queda como informe.',
    agencyExample: 'Ejemplo: después de observar dificultades en prospectos, se reformula la estructura de las propuestas para hacerlas más claras y a medida.',
    weight: 1,
  },
  {
    id: 'craft_quality',
    dimension: 'craft',
    title: 'Calidad creativa consistente',
    description: 'La ejecución visual, narrativa y de experiencia mantiene un estándar claro y competitivo.',
    tooltip: 'Busca ver si la calidad aparece de forma consistente y no solo en proyectos aislados.',
    agencyExample: 'Ejemplo: presentaciones, propuestas, contenidos y entregables mantienen nivel de claridad, jerarquía y solidez en distintas cuentas.',
    weight: 1.1,
  },
  {
    id: 'craft_systems',
    dimension: 'craft',
    title: 'Patrones, templates y sistemas',
    description: 'Existen herramientas reutilizables que permiten sostener calidad sin empezar todo de cero.',
    tooltip: 'Evalúa si el sistema ayuda a escalar la calidad creativa.',
    agencyExample: 'Ejemplo: la agencia cuenta con templates, frameworks de storytelling o librerías visuales que aceleran trabajo sin bajar nivel.',
    weight: 1,
  },
  {
    id: 'craft_feedback',
    dimension: 'craft',
    title: 'Feedback útil sobre el trabajo',
    description: 'El feedback de craft ayuda a mejorar claridad, experiencia, narrativa y consistencia.',
    tooltip: 'No se trata de “me gusta / no me gusta”, sino de crítica útil para mejorar.',
    agencyExample: 'Ejemplo: una revisión de propuesta comercial observa lógica de lectura, empatía con el cliente y consistencia narrativa.',
    weight: 1,
  },
  {
    id: 'craft_tooling',
    dimension: 'craft',
    title: 'Herramientas que acompañan la calidad',
    description: 'El equipo tiene herramientas y prácticas que permiten producir con velocidad y estándar consistente.',
    tooltip: 'Mide si la operación favorece o frena el buen trabajo creativo.',
    agencyExample: 'Ejemplo: el equipo usa herramientas compartidas, librerías y plantillas que facilitan trabajar mejor y más rápido.',
    weight: 0.9,
  },
  {
    id: 'craft_accessibility',
    dimension: 'craft',
    title: 'Claridad y experiencia del entregable',
    description: 'Los entregables son claros, legibles, bien secuenciados y fáciles de entender para clientes y prospectos.',
    tooltip: 'Evalúa si el diseño hace que la solución se entienda y genere confianza.',
    agencyExample: 'Ejemplo: una presentación comercial ayuda al prospecto a entender el problema, la solución y el valor en pocos minutos.',
    weight: 1,
  },
  {
    id: 'operations_capacity',
    dimension: 'operations',
    title: 'Capacidad acorde a la demanda',
    description: 'La carga de trabajo del equipo es razonable respecto del volumen y complejidad de lo que se pide.',
    tooltip: 'Mide si el sistema puede sostener calidad sin agotamiento ni improvisación continua.',
    agencyExample: 'Ejemplo: el equipo no vive apagando incendios permanentemente y puede dedicar tiempo a pensar, no solo a producir.',
    weight: 1,
  },
  {
    id: 'operations_roles',
    dimension: 'operations',
    title: 'Roles y responsabilidades claros',
    description: 'Cada persona y área entiende qué decide, qué entrega y cómo se articula con otros.',
    tooltip: 'Sin claridad de roles, el sistema genera fricción, duplicación y vacíos.',
    agencyExample: 'Ejemplo: se sabe quién lidera discovery, quién baja la narrativa, quién define experiencia y quién hace seguimiento.',
    weight: 1,
  },
  {
    id: 'operations_visibility',
    dimension: 'operations',
    title: 'Visibilidad operativa',
    description: 'Se ve con claridad qué está en curso, qué es prioritario, qué está trabado y dónde hay sobrecarga.',
    tooltip: 'La visibilidad permite decidir mejor y evitar cuellos de botella.',
    agencyExample: 'Ejemplo: el equipo puede ver backlog, prioridades, deadlines y bloqueos sin depender de conversaciones aisladas.',
    weight: 1,
  },
  {
    id: 'operations_learning',
    dimension: 'operations',
    title: 'Desarrollo de talento',
    description: 'Existe una lógica de coaching, aprendizaje y crecimiento para fortalecer capacidades de diseño y pensamiento de diseño.',
    tooltip: 'Mide si el talento se desarrolla de forma intencional y no solo por exposición al trabajo.',
    agencyExample: 'Ejemplo: se trabaja sobre habilidades de customer centric, storytelling, research, facilitación o service thinking.',
    weight: 0.9,
  },
  {
    id: 'operations_governance',
    dimension: 'operations',
    title: 'Gobierno y seguimiento',
    description: 'Hay reglas claras para decidir, priorizar, escalar bloqueos y dar seguimiento a la mejora continua.',
    tooltip: 'Busca ver si la transformación depende de voluntad individual o si ya tiene estructura de gobierno.',
    agencyExample: 'Ejemplo: existe una rutina visible donde se revisan avances, frenos, aprendizajes y próximos pasos de la transformación.',
    weight: 1.1,
  },
];
