import { DimensionKey, GlossaryTerm, Question, ScaleOption } from '@/lib/types';

export const AGENCIES = [
  'ROGER',
  'LUPE',
  'AMPLIFY',
  'OMD',
  'NASTA',
  'BRICK',
  'ROW',
  'BPR',
] as const;

export const DIMENSIONS: DimensionKey[] = [
  'visionary',
  'inspirational',
  'relational',
  'identity',
  'adoption',
  'innovation',
];

export const DIMENSION_LABELS: Record<DimensionKey, string> = {
  visionary: 'Liderazgo visionario',
  inspirational: 'Liderazgo inspiracional',
  relational: 'Liderazgo relacional',
  identity: 'Diseño como identidad',
  adoption: 'Adopción del diseño',
  innovation: 'Innovación por diseño',
};

export const DIMENSION_DESCRIPTIONS: Record<DimensionKey, string> = {
  visionary: 'Cómo la dirección define, patrocina y ajusta una visión de innovación centrada en usuarios, clientes y audiencias.',
  inspirational: 'Cómo los líderes modelan comportamientos design-led, se conectan con usuarios, permiten aprender del error y celebran buenas prácticas.',
  relational: 'Cómo se construye seguridad psicológica, escucha activa y conversaciones que facilitan la adopción cultural del diseño.',
  identity: 'Cómo la orientación a usuarios queda incorporada en valores, decisiones de personas, prácticas y voz del usuario.',
  adoption: 'Cómo el diseño se vuelve simple, usable y cotidiano para todos, incluyendo procesos internos, autonomía y rituales de desarrollo.',
  innovation: 'Cómo la agencia prototipa, aprende rápido, combina perspectivas, tolera ambigüedad y mejora continuamente.',
};

export const DIMENSION_INTROS: Record<DimensionKey, string> = {
  visionary: 'Este bloque evalúa si existe una dirección clara para innovar desde customer centricity, si los líderes la patrocinan y si la agencia puede ajustar estrategia cuando cambian las necesidades de clientes y audiencias.',
  inspirational: 'Acá miramos si la cultura design-led se ve en la conducta diaria de los líderes: cómo escuchan, cómo aprenden del error, cómo se acercan al usuario y cómo refuerzan ejemplos positivos.',
  relational: 'Este bloque observa si las personas pueden decir la verdad, aportar ideas y construir confianza para que la innovación no dependa solo de procesos, sino también de relaciones.',
  identity: 'Mide si el diseño y la orientación a usuarios son parte de la identidad real de la agencia: valores, decisiones de talento, lectura del ecosistema y representación sistemática del usuario.',
  adoption: 'Evalúa qué tan fácil es para cualquier equipo usar diseño en el día a día, mejorar procesos internos, tomar decisiones cerca del usuario y sostener rituales de aprendizaje.',
  innovation: 'Este bloque mide la capacidad operativa de innovar: prototipar, probar, aprender, combinar insights diversos, sostener ambigüedad y mejorar de forma continua.',
};

export const DIMENSION_WEIGHTS: Record<DimensionKey, number> = {
  visionary: 0.18,
  inspirational: 0.16,
  relational: 0.14,
  identity: 0.18,
  adoption: 0.16,
  innovation: 0.18,
};

export const SCALE_OPTIONS: ScaleOption[] = [
  { value: 1, shortLabel: 'Reactivo', title: '1 · Reactivo', description: 'No existe, depende de personas puntuales o aparece tarde.' },
  { value: 2, shortLabel: 'Emergente', title: '2 · Emergente', description: 'Sucede a veces, pero de forma inconsistente y con poca estructura.' },
  { value: 3, shortLabel: 'Definido', title: '3 · Definido', description: 'Existe de forma repetible en parte importante de la operación.' },
  { value: 4, shortLabel: 'Gestionado', title: '4 · Gestionado', description: 'Está sistematizado, se gestiona y se mide con cierta regularidad.' },
  { value: 5, shortLabel: 'Estratégico', title: '5 · Estratégico', description: 'Es una capacidad madura que influye en cultura, negocio y ventaja competitiva.' },
];

export const GLOSSARY_TERMS: GlossaryTerm[] = [
  {
    id: 'design-led-culture',
    term: 'Cultura design-led',
    definition: 'Cultura donde el diseño, la empatía, la experimentación y la comprensión de usuarios influyen en cómo se decide, se trabaja y se mejora.',
    appliedExample: 'En una agencia significa que no solo el equipo creativo usa diseño: cuentas, estrategia, medios, dirección y operaciones también toman decisiones desde usuarios y aprendizaje.',
  },
  {
    id: 'customer-centric',
    term: 'Customer centric',
    definition: 'Enfoque que organiza soluciones, procesos y experiencias alrededor de necesidades reales de clientes, usuarios, audiencias y equipos internos.',
    appliedExample: 'Implica adaptar propuestas, rituales, entregables y decisiones a cada cliente o audiencia en vez de repetir una lógica estándar.',
  },
  {
    id: 'voice-of-user',
    term: 'Voz del usuario',
    definition: 'Sistema para traer evidencia de usuarios a las conversaciones de decisión, no solo opiniones internas.',
    appliedExample: 'Puede ser feedback de clientes, entrevistas, data de campaña, reclamos, aprendizajes de cuentas o insights de audiencias presentes en reuniones clave.',
  },
  {
    id: 'psychological-safety',
    term: 'Seguridad psicológica',
    definition: 'Condición cultural donde las personas pueden decir la verdad, hacer preguntas, admitir errores y proponer ideas sin miedo a castigo o ridiculización.',
    appliedExample: 'Un planner o ejecutivo puede decir que el brief no está claro antes de producir, aunque eso incomode el cronograma.',
  },
  {
    id: 'prototype',
    term: 'Prototipo',
    definition: 'Versión temprana y de bajo costo de una idea, propuesta, proceso o servicio que permite aprender antes de invertir demasiado.',
    appliedExample: 'Antes de lanzar una nueva oferta comercial, la agencia prueba una versión simple con dos clientes o prospectos y ajusta según feedback.',
  },
  {
    id: 'ritual',
    term: 'Ritual de innovación',
    definition: 'Práctica recurrente que instala comportamientos deseados: revisión, aprendizaje, feedback, ideación, demo o retrospectiva.',
    appliedExample: 'Una reunión mensual donde equipos comparten aprendizajes de usuarios, experimentos y mejoras implementadas.',
  },
  {
    id: 'ecosystem',
    term: 'Ecosistema de usuarios',
    definition: 'Conjunto de personas impactadas por una solución: cliente, usuario final, equipos internos, proveedores, partners y audiencias.',
    appliedExample: 'Una propuesta para un anunciante también impacta al equipo de cuentas, medios, creatividad, reporting y a la audiencia que recibe la campaña.',
  },
  {
    id: 'ambiguity',
    term: 'Ambigüedad',
    definition: 'Etapa donde todavía no está claro cuál es el problema real o la solución correcta, y se necesita explorar antes de cerrar una respuesta.',
    appliedExample: 'Cuando un cliente pide “más innovación”, el equipo evita saltar a una campaña y primero entiende qué necesidad de negocio o experiencia hay detrás.',
  },
];

export const QUESTIONS: Question[] = [
  {
    id: 'p01_user_centric_vision',
    dimension: 'visionary',
    principleNumber: 1,
    principleName: 'Rally Around a User-Centric Vision',
    title: 'Visión customer centric compartida',
    description: 'La agencia tiene una visión clara de innovación y customer centricity que guía decisiones más allá de KPIs comerciales inmediatos.',
    tooltip: 'Mide si existe un norte común centrado en usuarios, clientes y audiencias, no solo objetivos de venta o entrega.',
    glossary: 'Una visión customer centric ayuda a que todos entiendan para quién se innova y qué valor se busca crear.',
    agencyExample: 'Ejemplo: al definir una nueva oferta, la conversación parte de qué problema real del cliente o audiencia se quiere resolver.',
    weight: 1.2,
  },
  {
    id: 'p02_leaders_sponsor_design',
    dimension: 'visionary',
    principleNumber: 2,
    principleName: 'Align Leaders to Champion and Sponsor Design',
    title: 'Líderes alineados y sponsors de diseño',
    description: 'Los líderes de la agencia patrocinan activamente el diseño, la innovación y el enfoque en usuarios con agenda, decisiones y recursos.',
    tooltip: 'No alcanza con decir que diseño importa: debe verse en reuniones, prioridades, presupuesto y seguimiento.',
    agencyExample: 'Ejemplo: dirección reserva tiempo para revisar iniciativas de innovación, desbloquear decisiones y pedir evidencia de usuarios.',
    weight: 1.15,
  },
  {
    id: 'p03_agile_strategy',
    dimension: 'visionary',
    principleNumber: 3,
    principleName: 'Be Agile to Adjust Strategy',
    title: 'Agilidad para ajustar estrategia',
    description: 'La agencia revisa y ajusta su estrategia cuando cambian necesidades de clientes, audiencias, tecnología o mercado.',
    tooltip: 'Evalúa si la agencia puede pivotar con aprendizaje real o queda atrapada en planes rígidos.',
    agencyExample: 'Ejemplo: una propuesta, servicio o proceso se ajusta después de detectar un cambio en hábitos de audiencia o expectativas del cliente.',
    weight: 1,
  },
  {
    id: 'p04_walk_the_talk',
    dimension: 'inspirational',
    principleNumber: 4,
    principleName: 'Walk the Talk and Model Design',
    title: 'Líderes que modelan comportamientos design-led',
    description: 'Los líderes practican en su propio comportamiento la empatía, la escucha, la colaboración y la orientación a usuarios que esperan del equipo.',
    tooltip: 'La cultura se instala cuando los líderes hacen visible el comportamiento esperado.',
    agencyExample: 'Ejemplo: un director no solo pide empatía con clientes, sino que participa en sesiones de escucha y usa esos aprendizajes para decidir.',
    weight: 1,
  },
  {
    id: 'p05_connect_with_users',
    dimension: 'inspirational',
    principleNumber: 5,
    principleName: 'Connect Directly with Users',
    title: 'Contacto directo con usuarios y clientes',
    description: 'Los líderes y equipos se conectan directamente con clientes, audiencias o usuarios internos para entender necesidades reales.',
    tooltip: 'No se trata solo de leer reportes: se valora la exposición directa a la experiencia del usuario.',
    agencyExample: 'Ejemplo: líderes escuchan devoluciones de clientes, participan en research o revisan experiencias reales de audiencias antes de definir prioridades.',
    weight: 1.1,
  },
  {
    id: 'p06_no_blame_failure',
    dimension: 'inspirational',
    principleNumber: 6,
    principleName: 'No Blame When Failure Occurs',
    title: 'Aprendizaje sin cultura de culpa',
    description: 'Cuando una iniciativa falla, el foco está en aprender y corregir el sistema, no en buscar culpables.',
    tooltip: 'La experimentación necesita límites claros, pero también seguridad para aprender de errores nuevos.',
    agencyExample: 'Ejemplo: después de una propuesta perdida, el equipo revisa hipótesis, proceso y feedback del cliente para mejorar, sin convertirlo en castigo.',
    weight: 1.05,
  },
  {
    id: 'p07_celebrate_design',
    dimension: 'inspirational',
    principleNumber: 7,
    principleName: 'Hunt for and Celebrate Design in Action',
    title: 'Celebración de diseño e innovación en acción',
    description: 'La agencia identifica, cuenta y reconoce historias donde el diseño, la empatía o la innovación generaron aprendizaje o impacto.',
    tooltip: 'Reconocer ejemplos concretos ayuda a que la cultura deje de ser abstracta.',
    agencyExample: 'Ejemplo: se comparte en reuniones internas un caso donde un insight del cliente cambió una solución y mejoró el resultado.',
    weight: 0.95,
  },
  {
    id: 'p08_safe_honesty',
    dimension: 'relational',
    principleNumber: 8,
    principleName: 'Make It Safe to be Honest with Leaders',
    title: 'Seguridad para hablar con honestidad',
    description: 'Las personas pueden decir la verdad sobre problemas, fricciones, errores o necesidades sin miedo a represalias.',
    tooltip: 'Sin honestidad, los líderes reciben una versión filtrada de la realidad y deciden peor.',
    agencyExample: 'Ejemplo: un equipo puede advertir que una solución no responde al cliente antes de avanzar, aunque eso implique reabrir una conversación.',
    weight: 1.1,
  },
  {
    id: 'p09_input_response',
    dimension: 'relational',
    principleNumber: 9,
    principleName: 'Invite Input and Respond Actively',
    title: 'Escucha activa y respuesta visible',
    description: 'La agencia no solo pide feedback: responde, explica decisiones y convierte aportes relevantes en acciones.',
    tooltip: 'La confianza crece cuando el equipo ve qué pasó con lo que aportó, incluso si una idea no se implementa.',
    agencyExample: 'Ejemplo: después de una retrospectiva, se comunican tres cambios concretos y por qué otros pedidos no entran en esta etapa.',
    weight: 1,
  },
  {
    id: 'p10_socialise_design',
    dimension: 'relational',
    principleNumber: 10,
    principleName: 'Socialise Design Through Conversations and Relationships',
    title: 'Diseño socializado en conversaciones',
    description: 'La adopción del diseño se trabaja mediante conversaciones, relaciones y pequeños espacios de influencia, no solo por bajadas formales.',
    tooltip: 'Muchas transformaciones avanzan cuando las ideas se socializan antes de exigir adopción masiva.',
    agencyExample: 'Ejemplo: antes de instalar un nuevo proceso de discovery, se conversa con cuentas, creatividad y medios para ajustar lenguaje y resistencias.',
    weight: 0.95,
  },
  {
    id: 'p11_values_people_practices',
    dimension: 'identity',
    principleNumber: 11,
    principleName: 'Embed Design in Your Values and People Practices',
    title: 'Diseño en valores y prácticas de personas',
    description: 'La empatía, la colaboración, la curiosidad y la mejora continua están reflejadas en selección, onboarding, evaluación y desarrollo.',
    tooltip: 'La cultura se sostiene cuando también vive en los sistemas de personas.',
    agencyExample: 'Ejemplo: al promover líderes se considera si impulsan colaboración, escucha e innovación, no solo resultados comerciales.',
    weight: 1,
  },
  {
    id: 'p12_core_identity',
    dimension: 'identity',
    principleNumber: 12,
    principleName: 'Make User Centricity Part of Your Core Identity',
    title: 'Customer centricity como identidad central',
    description: 'La orientación a usuarios es responsabilidad de todos los equipos, no solo de diseño, estrategia o research.',
    tooltip: 'Evalúa si customer centricity es un comportamiento transversal o una especialidad aislada.',
    agencyExample: 'Ejemplo: finanzas, cuentas, medios, creatividad y dirección pueden explicar quién es su usuario y cómo mejoran su experiencia.',
    weight: 1.15,
  },
  {
    id: 'p13_user_ecosystem',
    dimension: 'identity',
    principleNumber: 13,
    principleName: 'Holistically Serve the Ecosystem of Users',
    title: 'Lectura del ecosistema de usuarios',
    description: 'La agencia considera el impacto de sus soluciones en cliente, audiencia final, equipos internos, partners y operación completa.',
    tooltip: 'No se mira solo el punto de entrega: se entiende la cadena completa de valor y fricción.',
    agencyExample: 'Ejemplo: al rediseñar reporting, se piensa en cliente, equipo de cuentas, analítica, dirección y decisiones futuras.',
    weight: 1,
  },
  {
    id: 'p14_voice_of_user',
    dimension: 'identity',
    principleNumber: 14,
    principleName: 'Systematically Advocate the Voice of the User',
    title: 'Voz del usuario en decisiones',
    description: 'Existen mecanismos para que evidencia de usuarios, clientes o audiencias esté presente en reuniones y decisiones clave.',
    tooltip: 'La voz del usuario debe ser sistemática, no anecdótica ni dependiente de una persona.',
    agencyExample: 'Ejemplo: toda propuesta importante incluye aprendizajes de cliente/audiencia y no solo supuestos internos.',
    weight: 1.1,
  },
  {
    id: 'p15_simple_design',
    dimension: 'adoption',
    principleNumber: 15,
    principleName: 'Make Design Simple for Everyone to Use',
    title: 'Diseño simple y accesible para todos',
    description: 'La agencia traduce diseño e innovación en pasos, herramientas y comportamientos simples que cualquier equipo puede usar.',
    tooltip: 'Evita que diseño parezca una teoría compleja o exclusiva de especialistas.',
    agencyExample: 'Ejemplo: existe una guía simple para discovery, prototipado o retrospectiva que cuentas y medios pueden aplicar sin depender de un experto.',
    weight: 1,
  },
  {
    id: 'p16_design_internally',
    dimension: 'adoption',
    principleNumber: 16,
    principleName: 'Use Design Internally, Not Just Externally',
    title: 'Diseño aplicado a procesos internos',
    description: 'La agencia usa diseño para mejorar la experiencia de los propios equipos, no solo entregables para clientes.',
    tooltip: 'Lo que se vive internamente refuerza o contradice lo que se promete externamente.',
    agencyExample: 'Ejemplo: se rediseña el proceso de brief, onboarding o aprobación desde la experiencia de quienes lo usan todos los días.',
    weight: 1,
  },
  {
    id: 'p17_autonomy',
    dimension: 'adoption',
    principleNumber: 17,
    principleName: 'Empower Employees with Autonomy to Meet Users’ Needs',
    title: 'Autonomía para resolver necesidades',
    description: 'Los equipos tienen suficiente autoridad, criterios y recursos para tomar decisiones cercanas al usuario sin pedir permiso para todo.',
    tooltip: 'Autonomía no es ausencia de control: implica metas claras, límites y confianza en el contexto del equipo.',
    agencyExample: 'Ejemplo: un equipo puede ajustar una dinámica de presentación o testear una mejora con cliente sin esperar una cadena larga de aprobaciones.',
    weight: 1.05,
  },
  {
    id: 'p18_rituals_development',
    dimension: 'adoption',
    principleNumber: 18,
    principleName: 'Reinforce Design Through Employee Development and Engagement Rituals',
    title: 'Rituales de desarrollo y engagement',
    description: 'La agencia refuerza diseño e innovación mediante rituales recurrentes de aprendizaje, feedback, comunidad y desarrollo de capacidades.',
    tooltip: 'La cultura necesita repetición intencional, no solo una capacitación puntual.',
    agencyExample: 'Ejemplo: hay huddles, demos, retrospectivas, espacios de casos o sesiones mensuales para compartir aprendizajes de innovación.',
    weight: 0.95,
  },
  {
    id: 'p19_launch_learn',
    dimension: 'innovation',
    principleNumber: 19,
    principleName: 'Launch Quick, Fail Quick, Learn Quick',
    title: 'Prototipar, fallar y aprender rápido',
    description: 'La agencia lanza versiones tempranas para aprender rápido antes de invertir demasiado tiempo o recursos en una solución final.',
    tooltip: 'Busca ver si se aprende con pruebas reales o se espera a tener algo perfecto.',
    agencyExample: 'Ejemplo: una nueva oferta o proceso se prueba primero con una cuenta piloto, se mide aprendizaje y luego se escala.',
    weight: 1.15,
  },
  {
    id: 'p20_diverse_insights',
    dimension: 'innovation',
    principleNumber: 20,
    principleName: 'Synergise Diversity of Insights Within the Organisation',
    title: 'Diversidad de perspectivas integrada',
    description: 'La agencia combina insights de distintas áreas, niveles y especialidades para construir soluciones más completas.',
    tooltip: 'La diversidad solo agrega valor cuando se integra en una solución coherente.',
    agencyExample: 'Ejemplo: una propuesta nueva incorpora mirada de cuentas, medios, data, creatividad, dirección y experiencia de cliente.',
    weight: 1,
  },
  {
    id: 'p21_ambiguity_roi',
    dimension: 'innovation',
    principleNumber: 21,
    principleName: 'Be Patient with Ambiguity to Reap the ROI of Design',
    title: 'Paciencia con la ambigüedad',
    description: 'La agencia sostiene espacios de exploración para encontrar el problema correcto antes de cerrar soluciones rápidas o mediocres.',
    tooltip: 'Evalúa si se tolera la exploración cuando todavía no hay una respuesta clara.',
    agencyExample: 'Ejemplo: frente a un pedido ambiguo del cliente, el equipo investiga y reformula el problema antes de vender una solución cerrada.',
    weight: 1,
  },
  {
    id: 'p22_improvement',
    dimension: 'innovation',
    principleNumber: 22,
    principleName: 'Adopt an Aggressive Attitude Towards Improvement',
    title: 'Mejora continua proactiva',
    description: 'La agencia busca mejorar de forma constante procesos, servicios y experiencias, incluso cuando algo ya funciona razonablemente bien.',
    tooltip: 'La innovación se sostiene con una actitud activa de mejora, no solo con grandes proyectos.',
    agencyExample: 'Ejemplo: cada trimestre se revisan aprendizajes de clientes, fricciones internas y oportunidades para mejorar servicios o procesos.',
    weight: 1.05,
  },
];
